# Generated by Django 5.2.8 on 2025-11-29 13:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0006_remove_productview_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(help_text='ID de la zone SVG (ex: area12, area18, etc.)', max_length=50, unique=True, verbose_name='ID de la zone')),
                ('nom', models.CharField(help_text='Nom descriptif de la zone (ex: FIT HOMME, NATATION)', max_length=200, verbose_name='Nom de la zone')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('couleur', models.CharField(blank=True, help_text="Code couleur hex pour l'affichage", max_length=20, null=True, verbose_name='Couleur de la zone')),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'affichage dans les listes", verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Zone active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone du magasin',
                'verbose_name_plural': 'Zones du magasin',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DemandeLocalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(blank=True, help_text="Catégorie ou sport recherché par l'utilisateur", max_length=200, null=True, verbose_name='Catégorie recherchée')),
                ('requete', models.TextField(help_text="Question posée par l'utilisateur", verbose_name='Requête utilisateur')),
                ('reponse', models.TextField(blank=True, null=True, verbose_name='Réponse fournie')),
                ('success', models.BooleanField(default=True, help_text='Indique si une localisation a été trouvée', verbose_name='Localisation trouvée')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interaction_chatbot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_localisation', to='dashboard.chatbotinteraction', verbose_name='Interaction chatbot associée')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_localisation', to='dashboard.product', verbose_name='Produit recherché')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_localisation', to='dashboard.session', verbose_name='Session utilisateur')),
                ('zone_trouvee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='localisation_produits.zonemagasin', verbose_name='Zone trouvée')),
            ],
            options={
                'verbose_name': 'Demande de localisation',
                'verbose_name_plural': 'Demandes de localisation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueLocalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('nombre_recherches', models.IntegerField(default=0, help_text='Nombre de fois où cette zone a été recherchée', verbose_name='Nombre de recherches')),
                ('nombre_clics', models.IntegerField(default=0, help_text='Nombre de clics sur la zone dans la carte', verbose_name='Nombre de clics')),
                ('nombre_produits_vus', models.IntegerField(default=0, help_text='Nombre de produits consultés dans cette zone', verbose_name='Produits consultés')),
                ('temps_moyen_recherche', models.FloatField(blank=True, null=True, verbose_name='Temps moyen de recherche (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='localisation_produits.zonemagasin', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Statistique de localisation',
                'verbose_name_plural': 'Statistiques de localisation',
                'ordering': ['-date', 'zone'],
                'unique_together': {('date', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='LocalisationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rayon', models.CharField(blank=True, help_text='Code ou numéro du rayon', max_length=50, null=True, verbose_name='Rayon')),
                ('etagere', models.CharField(blank=True, help_text="Niveau d'étagère (ex: A, B, C ou 1, 2, 3)", max_length=50, null=True, verbose_name='Étagère')),
                ('position', models.CharField(blank=True, help_text="Position précise sur l'étagère", max_length=50, null=True, verbose_name='Position')),
                ('quantite_stock', models.IntegerField(default=0, help_text='Quantité disponible à cet emplacement', verbose_name='Quantité en stock')),
                ('derniere_verification', models.DateTimeField(blank=True, help_text='Date de la dernière vérification du stock', null=True, verbose_name='Dernière vérification')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('active', models.BooleanField(default=True, verbose_name='Localisation active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='dashboard.product', verbose_name='Produit')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='localisation_produits.zonemagasin', verbose_name='Zone du magasin')),
            ],
            options={
                'verbose_name': 'Localisation de produit',
                'verbose_name_plural': 'Localisations de produits',
                'ordering': ['zone', 'rayon', 'etagere'],
                'unique_together': {('product', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='CategorieLocalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(db_index=True, help_text='Nom du sport ou de la catégorie (ex: Natation, Running, etc.)', max_length=200, verbose_name='Sport/Catégorie')),
                ('categorie', models.CharField(blank=True, help_text='Sous-catégorie spécifique (ex: Maillots de bain, Chaussures de running)', max_length=200, null=True, verbose_name='Sous-catégorie')),
                ('rayon', models.CharField(blank=True, help_text='Numéro ou code du rayon spécifique', max_length=200, null=True, verbose_name='Numéro de rayon')),
                ('etagere', models.CharField(blank=True, help_text="Indication de l'étage ou étagère", max_length=100, null=True, verbose_name='Étage/Étagère')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes supplémentaires')),
                ('active', models.BooleanField(default=True, verbose_name='Catégorie active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='localisation_produits.zonemagasin', verbose_name='Zone du magasin')),
            ],
            options={
                'verbose_name': 'Catégorie localisée',
                'verbose_name_plural': 'Catégories localisées',
                'ordering': ['sport', 'categorie'],
                'indexes': [models.Index(fields=['sport', 'zone'], name='localisatio_sport_6cd195_idx')],
            },
        ),
    ]
