# Generated by Django 5.2.7 on 2025-10-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotinteraction',
            name='satisfaction',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Niveau de satisfaction de l'utilisateur (en %)", null=True),
        ),
        migrations.AlterField(
            model_name='chatbotinteraction',
            name='model_used',
            field=models.CharField(default='Mistral', max_length=50),
        ),
    ]
