# Generated by Django 5.2.7 on 2025-10-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chatbotinteraction_satisfaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotinteraction',
            name='satisfaction',
            field=models.BooleanField(blank=True, help_text="L'utilisateur est-il satisfait ? (Oui/Non)", null=True),
        ),
    ]
