# Generated by Django 5.2.7 on 2025-10-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_chatbotinteraction_satisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='source',
            field=models.CharField(blank=True, help_text="Origine du clic (ex: 'carte', 'recherche', 'chatbot', etc.)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productview',
            name='zone',
            field=models.CharField(blank=True, help_text="Zone du magasin (ex: 'FIT HOMME', 'CHAUSSANT', etc.)", max_length=100, null=True),
        ),
    ]
