# Generated by Django 5.2.7 on 2025-10-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_productview_source_productview_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Borne tactile v2.1', max_length=100)),
                ('location', models.CharField(default='Decathlon Lille Centre', max_length=150)),
                ('code', models.CharField(default='BNL-021', max_length=50)),
                ('track_sessions', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('track_chatbot', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
