# Generated by Django 5.2.8 on 2025-11-29 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productview',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productview',
            name='product_name',
        ),
        migrations.AddField(
            model_name='chatbotinteraction',
            name='ask_feedback',
            field=models.BooleanField(default=False, help_text='Indique si un feedback utilisateur doit être demandé pour cette interaction'),
        ),
        migrations.AddField(
            model_name='chatbotinteraction',
            name='intent',
            field=models.CharField(blank=True, help_text='Intention détectée (ex: produit, magasin, livraison...)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatbotinteraction',
            name='response_success',
            field=models.BooleanField(default=True, help_text='La réponse du chatbot était-elle correcte / pertinente ?'),
        ),
        migrations.AddField(
            model_name='chatbotinteraction',
            name='response_time',
            field=models.FloatField(blank=True, help_text='Temps de génération de la réponse (secondes)', null=True),
        ),
        migrations.AddField(
            model_name='chatbotinteraction',
            name='sentiment',
            field=models.FloatField(blank=True, help_text='Analyse de sentiment (-1 = négatif, +1 = positif)', null=True),
        ),
        migrations.AlterField(
            model_name='chatbotinteraction',
            name='satisfaction',
            field=models.BooleanField(blank=True, help_text='Satisfaction binaire : Oui (True) / Non (False)', null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('sport', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_url_alt', models.URLField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='dashboard_p_name_91aa43_idx'), models.Index(fields=['brand'], name='dashboard_p_brand_efc578_idx'), models.Index(fields=['category'], name='dashboard_p_categor_6141dc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clicked', models.BooleanField(default=False, help_text="L'utilisateur a-t-il cliqué sur cette recommandation ?")),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='dashboard.chatbotinteraction')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_recommendations', to='dashboard.session')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_recommendations', to='dashboard.product')),
            ],
        ),
        migrations.AddField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='dashboard.product'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('system', 'Système'), ('export', 'Export'), ('analytics', 'Analytiques'), ('user', 'Utilisateur')], default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL vers laquelle rediriger', max_length=255, null=True)),
                ('action_label', models.CharField(blank=True, help_text="Libellé du bouton d'action", max_length=100, null=True)),
                ('icon', models.CharField(blank=True, help_text="Classe d'icône Bootstrap Icons", max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='dashboard_n_user_id_b572f4_idx'), models.Index(fields=['user', 'created_at'], name='dashboard_n_user_id_08051a_idx'), models.Index(fields=['notification_type'], name='dashboard_n_notific_47e787_idx')],
            },
        ),
    ]
