# Generated by Django 6.0 on 2025-12-05 19:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_click_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Refusée')], db_index=True, default='PENDING', max_length=20)),
                ('reason', models.TextField(help_text='Justification fournie par le manager')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de création de la demande')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text="Date de traitement par l'admin", null=True)),
                ('response_message', models.TextField(blank=True, help_text="Message optionnel de l'admin (surtout en cas de refus)", null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='product_price_gte_0',
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='requester',
            field=models.ForeignKey(help_text="Manager qui demande l'accès", on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin qui a traité la demande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_export_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['requester', 'status'], name='dashboard_e_request_642349_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['status', 'requested_at'], name='dashboard_e_status_292bff_idx'),
        ),
    ]
